# ----------------------------------------------------------------------------------------------------------------------
# Server configurations
# ----------------------------------------------------------------------------------------------------------------------

# Service configurations
server:
    port: 8899


#Bank Mock url
bankMock:
    url: http://localhost:10982

#Antifraud mock url
antifraudMock:
    url: http://localhost:10983

# Postgresql configuration
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/senior_test
        username: postgres
        password: postgres
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect

retry:
    database:
        maxAttempts: 5
        backoffDelay: 3000
    maxAttempts: 3
    backoffDelay: 1000