# ----------------------------------------------------------------------------------------------------------------------
# Server configurations
# ----------------------------------------------------------------------------------------------------------------------

# Service configurations
server:
    port: 8899


#Bank Mock url
bankMock:
    url: http://localhost:10982


# Postgresql configuration
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/senior_test
        username: postgres
        password: postgres
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
