# ----------------------------------------------------------------------------------------------------------------------
# Server configurations
# ----------------------------------------------------------------------------------------------------------------------

# Service configurations
server:
    port: 8899


#Bank Mock url
bankMock:
    url: http://localhost:10982


# ----------------------------------------------------------------------------------------------------------------------
# Redis Configuration
# ----------------------------------------------------------------------------------------------------------------------

redis:
    host: 127.0.0.1
    port: 6379
